version: '3'
services:

  spring-boot:
    image: aliberadzki/spring-with-actuator
    ports:
    - "8081:8080"
    container_name: aliberadzki-spring-with-actuator

  prometheus:
    image: prom/prometheus:v2.5.0
    ports:
    - "9091:9090"
    container_name: aliberadzki-prometheus
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
    - ./prometheus/etc/:/etc/prometheus/
    links:
    - spring-boot
  grafana:
    image: grafana/grafana:5.4.1
    ports:
      - 3001:3000
    links:
      - prometheus
    volumes:
      - ./grafana/etc/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
