{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (status)",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "JVM mem committed",
   "type": "singlestat",
   "description": "Total mem (heap + nonheap)",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes)/(1024*1024)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "description": "# Displays \nusage `of` CPU",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  }
 ]
}