global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    environment: production

scrape_configs:
- job_name: 'spring-boot-service'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['spring-boot:8080']
    labels:
      app: 'spring-boot'
      tier: 'front-end'
      env: 'production'